# XOR Model

This is a simple Keras model that solves the XOR problem - given two inputs, output 1 if they are the same, and 0 otherwise. 

This is trivial to do with any modern machine learning algorithm, but it will serve as a nice, simple model to use in the deployment example. 

Start by importing the relevant libraries. Also seed the RNG for repeatable results.

In [1]:
from keras.models import Sequential
from keras.layers.core import Dense, Activation
from keras.optimizers import Adam, SGD
import numpy as np

np.random.seed(100)

Using TensorFlow backend.


Define the model structure. This is the same as a standard shallow neural network. Note the initialization - because this network is so small, the default initializer of glorot_uniform gives bad results.

In [2]:
model = Sequential()
model.add(Dense(2, input_dim=2, kernel_initializer='glorot_normal'))
model.add(Activation('sigmoid'))
model.add(Dense(1, input_dim=2, kernel_initializer='glorot_normal'))
model.add(Activation('sigmoid'))
sgd = SGD(lr=0.1, decay=1e-6, momentum=0.9, nesterov=True)
model.compile(loss='binary_crossentropy', optimizer=sgd)

Define the datasets. Here, the data is so small we define it inline.

In [3]:
X = np.array([[0,0],[0,1],[1,0],[1,1]], "float32")
y = np.array([[0],[1],[1],[0]], "float32")

print('Train data:')
print(X)
print('')
print('Train labels:')
print(y)

Train data:
[[ 0.  0.]
 [ 0.  1.]
 [ 1.  0.]
 [ 1.  1.]]

Train labels:
[[ 0.]
 [ 1.]
 [ 1.]
 [ 0.]]


Fit the mode. This should give pretty good convergence. If you **really** want the output labels to be 0/1, you can crank up the number of epochs.

In [4]:
model.fit(X, y, epochs=400, batch_size=1)

Epoch 1/400
4/4 [==============================] - 0s - loss: 0.7813     
Epoch 2/400
4/4 [==============================] - 0s - loss: 0.7291     
Epoch 3/400
4/4 [==============================] - 0s - loss: 0.7397     
Epoch 4/400
4/4 [==============================] - 0s - loss: 0.7383     
Epoch 5/400
4/4 [==============================] - 0s - loss: 0.7408     
Epoch 6/400
4/4 [==============================] - 0s - loss: 0.7858     
Epoch 7/400
4/4 [==============================] - 0s - loss: 0.7970     
Epoch 8/400
4/4 [==============================] - 0s - loss: 0.7618     
Epoch 9/400
4/4 [==============================] - 0s - loss: 0.7574     
Epoch 10/400
4/4 [==============================] - 0s - loss: 0.7793     
Epoch 11/400
4/4 [==============================] - 0s - loss: 0.7242     
Epoch 12/400
4/4 [==============================] - 0s - loss: 0.7237     
Epoch 13/400
4/4 [==============================] - 0s - loss: 0.7619     
Epoch 14/400
4/4 [================

Check the model output. It should give something close to [0, 1, 1, 0].

In [5]:
print('Predictions:')
print(model.predict([[1,1], [1, 0], [0, 1], [0,0]]))

Predictions:
[[ 0.01143153]
 [ 0.98827809]
 [ 0.98104501]
 [ 0.01345657]]


Save the model to file.

In [6]:
model.save_weights('model.h5')
model_json = model.to_json()
with open('model.json', 'w') as f:
    f.write(model_json)